### ISSUE TITLE
渠道怎么配置呢？

### ISSUE THREAD

**Issue by wubangjunjava** [Yemesoft/AndroidTool#1]
渠道怎么配置呢？没看到教程，什么格式

**Comment by StrugglingAndroid** [comment]
和360加固的渠道配置文件一样就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月15日(星期五) 上午10:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Yemesoft/AndroidTool] 渠道怎么配置呢？ (Issue #1)














 
渠道怎么配置呢？没看到教程，什么格式

**Comment by wubangjunjava** [comment]
TR_CHANNEL_KEY 360应用平台 360
TR_CHANNEL_KEY 腾讯应用宝 qq
TR_CHANNEL_KEY 百度手机助手 baidu
TR_CHANNEL_KEY 豌豆荚 wandoujia
TR_CHANNEL_KEY 小米 xiaomi
TR_CHANNEL_KEY oppo手机 oppo
TR_CHANNEL_KEY 华为 huawei
TR_CHANNEL_KEY vivo vivo
TR_CHANNEL_KEY common common
TR_CHANNEL_KEY 抖音 dy


我这么配置有问题吗？

**Comment by wubangjunjava** [comment]
我用这个软件打包后，生成了小米渠道的包，反编译看了里面的这个值没有变化。
![Uploading 微信截图_20241115103736.png…]()

**Comment by wubangjunjava** [comment]
<meta-data android:name="TR_CHANNEL_KEY" android:value="common"/>

**Comment by StrugglingAndroid** [comment]
渠道不是通过meta-data标识的了，readme文档不是说了怎么获取渠道名么？

**Comment by wubangjunjava** [comment]
> 渠道不是通过meta-data标识的了，readme文档不是说了怎么获取渠道名么？

哦。 我明白了，我以为跟360一样呢。好的，谢谢

**Comment by StrugglingAndroid** [comment]
这个的原理是在apk里边加了一个文件名携带渠道信息的空文件

**Comment by wubangjunjava** [comment]
> 这个的原理是在apk里边加了一个文件名携带渠道信息的空文件

大神，真历害啊，360太恶心居然收费 了

**Comment by wubangjunjava** [comment]
很好用，谢谢
